
spring:
  datasource:    url: jdbc:mysql://localhost:3306/springboottesting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(PSOWzjcJ/MuR+tp9mXeWIs5CTPtGy1mO)
    initialization-mode: always
    schema: classpath:schema-mysql.sql
  jpa:    hibernate:      ddl-auto: none
 
logging: 
  file: logs/application.log 
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: WARN
    org.testcontainers: INFO
    org.hibernate: INFO
    root: INFO
    sql: INFO
    web: INFO
    
   
jasypt:
  encryptor: 
    password: test
    